from ast import Call
from typing import Callable

import numpy as np
from scipy.stats import ks_2samp

from sklearn.metrics import make_scorer

def ks(y_true : np.ndarray, y_pred : np.ndarray) -> float:
    """
    This function calculates the Kolmogorov-Smirnov statistic between two classes in a binary classifier.

    Args:
        y_true (np.array): An array containing the true values.
        y_pred (np.array): The predictions/scores generated by the model.

    Returns:
        float: The K-S statistic.
    """
    class0 = y_pred[y_true == 0]
    class1 = y_pred[y_true == 1]
    result = ks_2samp(class0, class1).statistic
    return result

ks_score : Callable[[np.ndarray, np.ndarray], float] = make_scorer(ks, needs_proba=True)